### ISSUE TITLE
noPrometheusMetrics should be PrometheusMetrics

### ISSUE THREAD

**Issue by orenwolf** [Kriechi/aws-s3-reverse-proxy#2]
It appears that your test for NoPrometheusMetrics needs to be "true" in order for the port to be created (i.e., the logic is reversed in main.go).

Thanks for writing a useful proxy for DirectConnect folk!

**Comment by Kriechi** [comment]
Thanks for reporting this! That obviously didn't make much sense.
Fixed by 999f45785df05e7d6c173f564cd37050c93a47d7

Glad to see somebody else faced similar problems and found this useful! 🎉
