### ISSUE TITLE
URL Encoding causes signature to be incorrect

### ISSUE THREAD

**Issue by ndxcarver** [Kriechi/aws-s3-reverse-proxy#3]
A URL that is coming in as `http://myproxy.com/year=2020/month=04/day=28/hour=20/test.txt` is being changed to `http://myproxy.com/year%3D2020/month%3D04/day%3D28/hour%3D20/test.txt` causing the signature not to be correct. I corrected this in my copy in **handler.go** adding the line `proxyURL.RawPath = *&req.URL.Path` in the **assembleUpstreamReq** function.

**Comment by Kriechi** [comment]
Thanks for reporting this! I needed to make a small additional change - see c753875.
Please let me know if this fixes your problem in your environment & use case!
